- name: Ping
  hosts: localhost
  connection: local
  become: yes

  tasks:

  - name: Task ping
    ping:
  - name: Install docker packages
    remote_user: ansible_ubuntu_demo
    apt:
      name: name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Add Docker s GPG key for ubuntu from official site
    remote_user: ansible_ubuntu_demo
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
